debug: true
 
proxy:
  coll: ${COLL}
  recording: true

  enable_banner: false
  enable_wombat: true

recorder:
  dedup_policy: skip
  source_coll: live
  cache: always
  rollover_size: ${ROLLOVER_SIZE}
  enable_put_custom_record: true

collections:
  live: $live

server:
  generateWARC: true
  combineWARC: true
  failOnFailedSeed: true
  workers: 3
  scopeType: page
  waitUntil: load,networkidle0
  timeout: 1000
  behaviorTimeout: 1000
  logging: stats,pywb
